### ISSUE TITLE
Use a default eslint and eslintConfig

### ISSUE THREAD

**Issue by zeke** [Flet/standard-engine#113]
The linter constructor doesn't seem to work without options:

```
❯ trymodule standard-engine
Package 'standard-engine' was loaded and assigned to 'standard_engine' in the current scope
REPL started...
> standard_engine
{ cli: [Function: Cli], linter: [Function: Linter] }

> const standard = standard_engine.linter()
Error: opts.eslint option is required
    at new Linter (/Users/zeke/.trymodule/node_modules/standard-engine/index.js:32:27)
    at Object.Linter (/Users/zeke/.trymodule/node_modules/standard-engine/index.js:26:41)
   ...
```

Passing in eslint and an empty object works though:

```
~/forks/standard-engine master* 25s
❯ node        
> const eslint = require('.')
undefined
> const standard = require('.').linter({eslint:eslint, eslintConfig: {}})
```

I think a nicer behavior would be to allow the options to be undefined, defaulting to vanilla eslint if unspecified.

**Comment by Flet** [comment]
This seems sensible, however `standard-engine` isn't really meant to be run directly on its own. 

Its really just the glue that connects a specific version of eslint with a specific config. The config itself drives which version of eslint is needed as rules can be added/changed every version. This also allows using other eslint implementations like `babel-eslint`.

**Comment by zeke** [comment]
Thanks, @Flet. I was a bit off-track, then realized `standard` has a programmatic API that suits my purposes: https://github.com/Flet/standard-engine/issues/114

Closing!
