### ISSUE TITLE
Linter is not producing warnings

### ISSUE THREAD

**Issue by zeke** [Flet/standard-engine#114]
Given the following:

```js
const standard = require('.').linter({eslint: require('eslint')})
standard.lintText('var a = 1;', function(err, res) { console.dir(res) })
```

I would expect to see something about an unneeded semicolon, but instead the result is:

```js
{ results: 
   [ { filePath: '<text>',
       messages: [],
       errorCount: 0,
       warningCount: 0 } ],
  errorCount: 0,
  warningCount: 0 }
```

Am I doing it wrong?

**Comment by zeke** [comment]
> Am I doing it wrong?

Yes. I was.

Turns out all I needed was `standard`, not `standard-engine`:

```js
require('standard').lintText('var a = 1;', function(err, res) { console.dir(res) })
```

**Comment by feross** [comment]
Yep -- sorry if this was confusing. `standard-engine` is more generic. Meant for people to create their own `standard`-like modules. This core is shared by `standard` and `semistandard`, for example.

**Comment by zeke** [comment]
Yeah I should have RTFM. I saw the name `standard-engine` and made some quick assumptions. Happy that vanilla standard works for me! I made this: https://github.com/zeke/standard-markdown
