### ISSUE TITLE
glob for ignore files from CLI

### ISSUE THREAD

**Issue by Kikobeats** [Flet/standard-engine#116]
by default some common files will be ignored, but this functionality is not exposed in the CLI for add more files to be ignored (or I didn't found documentation about that).

**Comment by Flet** [comment]
The deglob package is used for determining which files to ignore:
>Take a list of glob patterns and return an array of file locations, respecting .gitignore and allowing for ignore patterns via package.json.

Its possible to add files to ignore via `package.json`

````js
"pocketlint": { // this key should equal the value of cmd in options.js
  "ignore": [
    "**/out/",
    "/lib/select2/",
    "/lib/ckeditor/",
    "tmp.js"
  ]
}
````

You're correct that the default `bin.js` does not expose this, but it should not be too hard to write a custom one :)

**Comment by feross** [comment]
I would accept a PR that added this to the CLI. What do you think @Flet?

Either way, IMO this isn't that important so I'm going to close this. PR welcome :)
