### ISSUE TITLE
Specifying parserOptions for ESLint

### ISSUE THREAD

**Issue by msegado** [Flet/standard-engine#127]
`standard-engine` supports custom parsers (e.g. `babel-eslint`), but it would also be nice if it allowed us to set the parser options in ESLint's default parser. My particular use case is enabling standard ES7 features so I can use the exponentiation operator:

```json
{
    "parserOptions": {
        "ecmaVersion": 7
    }
}
```

Thanks for your work on this project, by the way!

**Comment by Flet** [comment]
It should be possible to add these to the `opts.eslintConfig` json thats passed in. Does that work?

**Comment by Flet** [comment]
Side note: the latest version of eslint supports ES7 out of the box. `eslint-config-standard` was just updated to use this too: https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json#L2

Does this help you?

Related `standard` thread:
https://github.com/feross/standard/issues/639

**Comment by msegado** [comment]
Oh wow, that's perfect - thank you for letting me know!

**Comment by feross** [comment]
> Side note: the latest version of eslint supports ES7 out of the box.

Unfortunately, you still have to specify `"parserOptions": { "ecmaVersion": 7 }` since ES5 is the default.

**Comment by feross** [comment]
As @Flet says, just include the `parserOptions` line in the eslintConfig file json that you pass into `standard-engine`.
