### ISSUE TITLE
Support filename in lintText?

### ISSUE THREAD

**Issue by novemberborn** [Flet/standard-engine#131]
It'd be cool if `lintText()` could support a `filename` argument, to be forwarded to [`executeOnText`](http://eslint.org/docs/developer-guide/nodejs-api#executeontext). For backwards compatibility reasons it could be a fourth argument, after `cb`.

I can make this change if you're interested.

(More ambitiously, perhaps breaking changes could be made along the board.)

**Comment by novemberborn** [comment]
Forgot to mention quite *why* this would be cool. Plugins like https://github.com/benmosher/eslint-plugin-import require the filename to work.

**Comment by Flet** [comment]
An argument after `cb` is not ideal :/

Would it be OK to add it to the `opts` argument? (`opts.filename` maybe?)

**Comment by novemberborn** [comment]
> An argument after cb is not ideal :/

Yea…

> Would it be OK to add it to the opts argument? (opts.filename maybe?)

I'm concerned that it'd subsequently be processed by `parseOpts()`. Maybe that's harmless?

**Comment by Flet** [comment]
It should be OK. `parseOpts` essentially builds `opts.eslintConfig` from a few specific keys. Passing along another key should not affect it.
