### ISSUE TITLE
Pluggable formatter?

### ISSUE THREAD

**Issue by novemberborn** [Flet/standard-engine#133]
The CLI output is quite barren. Formatters like https://github.com/sindresorhus/eslint-formatter-pretty provide more readable output. It'd be neat if the formatter could be configured.

I can do a PR for this if you're interested.

**Comment by Flet** [comment]
There are a few output formatters available, but these all work by piping the output
https://github.com/feross/awesome-standard#pretty-terminal-output-reporters

I didn't realize eslint has plugins for output formatting, neat!

Yeah, I like this idea. It would be really nice to build a default formatter that mimics the current output style. Then we can allow it to be overridden via eslint configuration maybe?

**Comment by novemberborn** [comment]
It's not an option in the ESLint configuration so we'd have to implement this in `bin/cmd.js`, but ESLint can help. 

* First we'd need a reference to the engine and the results: https://github.com/eslint/eslint/blob/56a662b4ebccf9e50acddcec38816060c89e8f5b/lib/cli.js#L183
* We can retrieve the formatter from the engine: https://github.com/eslint/eslint/blob/56a662b4ebccf9e50acddcec38816060c89e8f5b/lib/cli.js#L74
* And then it's a simple call to get a string: 
https://github.com/eslint/eslint/blob/56a662b4ebccf9e50acddcec38816060c89e8f5b/lib/cli.js#L80

There's no clean way to pass options like `--verbose` to the formatter (see http://eslint.org/docs/developer-guide/working-with-custom-formatters#passing-arguments-to-formatters) so instead we should fall back to the current reporter if none is configured. This is what XO does: https://github.com/sindresorhus/xo/blob/3c428474cd51579ed55ac94f8e9a467cd48fe9ac/cli.js#L84.

I'm unsure `standard-engine` needs to support a `-f`/`--formatter` option. I think that choice should be left to the libraries that build on top of `standard-engine`. Instead we should allow the formatter to be provided as an option in `options.js`. We could support strings and functions.

**Comment by feross** [comment]
I explicitly don't want formatters to be a part of `standard`. If you want to customize a formatter, that's not very far from also customizing rules. People who want configuration should probably just use eslint directly, or pipe the output to a formatter.

I know `standard-engine` has other users, but it's primary purpose is to serve `standard`, so I'm -1 on this.

**Comment by novemberborn** [comment]
> I know standard-engine has other users, but it's primary purpose is to serve standard so I'm -1 on adding this here.

It is a useful interface for building more specific linting tools, yes.

#138 did not introduce any code for making the formatter configurable by end-users. Just by consuming tools. I feel that strikes the balance between letting `standard-engine` support `standard`, but letting others write a more specific linting tool.
