### ISSUE TITLE
eslint-plugin-ava

### ISSUE THREAD

**Issue by mightyiam** [Flet/standard-engine#139]
Will a PR for inclusion of [esling-plugin-ava](https://github.com/avajs/eslint-plugin-ava) be welcomed?

**Comment by mightyiam** [comment]
@Flet @feross I know everyone is busy. I'm just asking whether pull-requests and issues that are not in feross/standard are being looked at by someone. Should I get more eyes on this by creating an issue in feross/standard?

**Comment by feross** [comment]
It doesn't make sense for that eslint plugin or any other one to be in this package. This package doesn't define any rules.
