### ISSUE TITLE
Installation fails on Node 0.10

### ISSUE THREAD

**Issue by timdp** [Flet/standard-engine#14]
All my Travis tests on Node 0.10 have been failing since yesterday ([example](https://travis-ci.org/timdp/es6-promise-pool/jobs/80873491)) because npm 1.4.28 is unable to install the dependency on `"https://github.com/eslint/eslint.git#9d6223040316456557e0a2383afd96be90d28c5a"`. It raises a pretty cryptic "not a package" error on the download.

I can reproduce this on my Windows machine if I install those same versions and install `standard-engine`, so I guess there's a syntax issue. As per [the docs](https://docs.npmjs.com/files/package.json#github-urls), I think abbreviating the URL to `"eslint/eslint#9d6223040316456557e0a2383afd96be90d28c5a"` would make it more compatible.

**Comment by feross** [comment]
We plan to remove the git dependency tomorrow when eslint publishes a new version. Sorry about this -- we won't use git dependencies in the future.

**Comment by timdp** [comment]
I'm not opposed to Git dependencies, but it'd be great if they were compatible with older Nodes.

**Comment by feross** [comment]
Git dependencies sometimes cause problems on Windows too - I've seen issues
in the past. After we get rid of this one, we should try to avoid
reintroducing them in the future.

In an environment where you control the version of node used and the
firewall settings, they can work fine. But they always seem to cause
problems in published packages, unfortunately.

**Comment by nexdrew** [comment]
Encountered the same problem with recent yargs builds, only affecting Node 0.10 and 0.11: https://travis-ci.org/bcoe/yargs/builds/80952390

Looking forward to the fix.

**Comment by timdp** [comment]
At the risk of going off topic: I'm on Windows and I don't really see a reason why Git dependencies wouldn't work as long as they use HTTP(S) transport. Of course, that's assuming that npm is able to translate `eslint/eslint` to the associated HTTPS repo URL. I'd be more worried about people who don't have Git installed. Anyway, referencing Git commits rather than version numbers mainly feels like a bad practice.

**Comment by Flet** [comment]
Thanks to @watson's #15 PR, this should be fixed. Can anyone verify?

**Comment by nexdrew** [comment]
@Flet @mafintosh @watson Verified. Was able to successfully install `standard@5.3.0` with `standard-engine@2.1.1` on Node v0.10.40. Thanks! :fireworks: :confetti_ball: :tada:

**Comment by timdp** [comment]
Confirmed! Feel free to close.

**Comment by Flet** [comment]
:tada:

**Comment by timdp** [comment]
For what it's worth: I just noticed that socket.io, which is quite a popular project, [also has GitHub dependencies](https://github.com/socketio/socket.io/blob/21ea31a34e0bb83a7aab8f4ff2f6f3c665bb816a/package.json#L24-L27) using the abbreviated form. Not saying I like it, but it doesn't seem to be causing them a lot of trouble either.

**Comment by feross** [comment]
@timdp Good to know. I think that abbreviated form doesn't work in really old versions of node 0.10, but yeah, probably okay to drop support for those now.
