### ISSUE TITLE
Options passed to standard-engine should not be overridden by package.json

### ISSUE THREAD

**Issue by novemberborn** [Flet/standard-engine#141]
As per https://github.com/Flet/standard-engine/pull/134#discussion_r85782733 globals, plugins and environments specified in `package.json` should not override the options passed into `standard-engine` itself.

**Comment by feross** [comment]
Just confirming this is an issue.

**Comment by feross** [comment]
See comment https://github.com/Flet/standard-engine/pull/146#issuecomment-272422326
