### ISSUE TITLE
Invalid char in console.log()

### ISSUE THREAD

**Issue by drazisil** [Flet/standard-engine#142]
https://github.com/Flet/standard-engine/blob/master/bin/cmd.js#L48

This is causing a number of my project builds to fail. Can it be corrected?

```

/home/ubuntu/jpm-report/node_modules/standard/node_modules/standard-engine/bin/cmd.js:48
    console.log(`
                ^
SyntaxError: Unexpected token ILLEGAL
```

**Comment by Flet** [comment]
Ah, this is a node v4 feature... We dropped support for 0.10 and 0.12 recently because eslint 3 required it.  Are you using a older version of node? Could you try upgrading?

**Comment by drazisil** [comment]
Sure, which version do you recomend?

**Comment by feross** [comment]
Use at least Node.js 4. If you can, I recommend using Node.js 6.
