### ISSUE TITLE
Q: why a non-default cache location?

### ISSUE THREAD

**Issue by mightyiam** [Flet/standard-engine#149]
Is there any benefit in [this](https://github.com/Flet/standard-engine/blob/996e7d9ef8b4186c840a7439f82950c89efbf2dc/index.js#L36), please?

**Comment by novemberborn** [comment]
What would be a default cache location to you?

**Comment by mightyiam** [comment]
According to [CLIEngine docs](http://eslint.org/docs/developer-guide/nodejs-api#cliengine) the default seems to be `.eslintcache`.

So, what’s the benefit of using a non-default. I didn’t read the ESLint code for that. Am hoping that someone already knows.

**Comment by novemberborn** [comment]
> So, what’s the benefit of using a non-default. I didn’t read the ESLint code for that. Am hoping that someone already knows.

I think ESLint might create that file in the project directory. The decision that was made here at least avoids that.

**Comment by feross** [comment]
Yep, @novemberborn is correct. We don't want to litter temporary cache files all over the system, but we still want the speed benefits of caching. I think this is better behavior than ESLint's default.
