### ISSUE TITLE
Add lintTextSync method?

### ISSUE THREAD

**Issue by tunnckoCore** [Flet/standard-engine#156]
It's not cool that `.lintText` requires a callback and ESLint's method is synchronous, but we here force `cb` for no reason. Or okey, at least add `.lintTextSync` method?

There is existing problem for https://github.com/dtinth/atom-prettier-standard-formatter, which is based on https://github.com/dtinth/prettier-standard-formatter, which uses promises, exactly because the `standard`s lintText method.

ping @dtinth, stay tuned :)

**Comment by feross** [comment]
Fair point. There's no need for this to be async. PR here: https://github.com/Flet/standard-engine/pull/157

**Comment by tunnckoCore** [comment]
cool, thanks

**Comment by feross** [comment]
FYI, this PR affects the `lintText` method: https://github.com/Flet/standard-engine/pull/159
