### ISSUE TITLE
Basic complete usage example.

### ISSUE THREAD

**Issue by FranzSkuffka** [Flet/standard-engine#161]
What is the minimal set up to get basic standard-linting within node.js?

When I use a `new Linter({eslint, eslintConfig: {"extends": ["standard"]}})` to `lintTextSync` some non-standard String, I get
```
{ results: 
   [ { filePath: '<text>',
       messages: [],
       errorCount: 0,
       warningCount: 0 } ],
  errorCount: 0,
  warningCount: 0 }
```

How do I get standard to show me that something is wrong with my code?

**Comment by Flet** [comment]
For standard style specifically:

```
var standard = require('standard');

var output = standard.lintTextSync('var x = 1;');
console.log(JSON.stringify(output));
```
If using `standard-engine` the config should be passed via the `configFile` key in the options object. Unfortunately, I don't think there is a way to use "extends" in plain old JSON. It has to be via a file.

example using standard-engine:
```js
// using standard-engine directly
var Linter = require('standard-engine').linter;

var opts = {
  eslint: require('eslint'),
  eslintConfig: {
    configFile: './node_modules/eslint-config-standard/eslintrc.json'
    // this could also be a local JSON file that has the "extends" 'standard' line in it
  }
};

var linter = new Linter(opts);

var engineOutput = linter.lintTextSync('var x = 1;');
console.log('\n\nengine output:');
console.log(JSON.stringify(engineOutput));
```

**Comment by FranzSkuffka** [comment]
Ah, did I miss the docs for this somewhere?
I was first looking for the node API in the `standard` repo.

**Comment by feross** [comment]
@FranzSkuffka The Node.js API for `standard` is documented here: https://github.com/feross/standard/#is-there-a-nodejs-api

**Comment by feross** [comment]
(Closing, as I think @FranzSkuffka's issue is resolved. If not, we can re-open)

**Comment by FranzSkuffka** [comment]
Thank you for the support.
