### ISSUE TITLE
Atom plugin for standard-engine linters.

### ISSUE THREAD

**Issue by gustavnikolaj** [Flet/standard-engine#162]
@novemberborn and I have been at work creating an [Atom linter plugin for standard-engine based linters](https://atom.io/packages/linter-js-standard-engine) ([GitHub repo](https://github.com/gustavnikolaj/linter-js-standard-engine)).

It supports a few popular standard-engine implementations out of the box, but can support any compatible linter through configuration in the projects package.json file. The main selling point of this specific plugin, besides that it is working for any standard-engine based linter, is that it will run the version installed in your project and does not bundle a few specific versions into itself.

I see that you don't have any editor specific integrations listed, which makes sense as this project is not targeting "end-users", but I thought that it might be useful to add a note here for any other people that maintain big or small standard-engine linters. Either just through this issue, or maybe even as a note in the README file. I would love to send a PR if it's anything you'd be interested in. :-)

**Comment by Flet** [comment]
Cool! Yeah I think it would be fine to add to the README.

**Comment by gustavnikolaj** [comment]
Replacing this issue with the PR referenced above.
