### ISSUE TITLE
Unused file 

### ISSUE THREAD

**Issue by ricardofbarros** [Flet/standard-engine#3]
I think the file `bin/standard-engine-cmd.js` isn't currently being used by anything.

**Comment by Flet** [comment]
Indeed, I was using it to test directly in the beginning, but its not used as of now.

**Comment by ricardofbarros** [comment]
I'm doing a PR for #2 and since I'm doing that I'll avail to do this.

**Comment by Flet** [comment]
:+1:

**Comment by Flet** [comment]
closed by commit https://github.com/Flet/standard-engine/commit/2819a26fdf8ed0a5a37e9e7850cdc9a7114976b4
