### ISSUE TITLE
Where is ignore from package read?

### ISSUE THREAD

**Issue by gustavnikolaj** [Flet/standard-engine#33]
I seem to have stared myself blind at the code. I cannot seem to find where you read the values of package.json "lintername".ignore and use that to extend the list of default ignores. It seems that the only values read from package.json is parser and globals?

https://github.com/Flet/standard-engine/blob/master/index.js#L128-L137

I verified that it works with ignoring, so I'm obviously missing something. I'd appreciate it, if you would point me in the right direction :-)

**Comment by gustavnikolaj** [comment]
Sorry about that. Sometimes, all you need to find the answer is to ask a question :-)

https://www.npmjs.com/package/deglob

**Comment by Flet** [comment]
No problem! Yeah the package.json reading kinda buried in deglob :)
