### ISSUE TITLE
Override files list with globs

### ISSUE THREAD

**Issue by joshuajabbour** [Flet/standard-engine#84]
I'm trying to override the files list, to include bin scripts. I'd like to use `['**/*.js', '**/*.jsx', 'bin/*']`, but the globs get expanded before they ever get here (by bash I assume). Which means what is matched is significantly different from what the glob module would match (and varies per the user's bash profile). 

Maybe this is an issue with how to format the files string for glob, but I cannot get any variation of `standard **/*.js **/*.jsx bin/*` to work (no matter how I format or escape it. Any thoughts?

**Comment by Flet** [comment]
This line is working for me:

```
standard **/*.js **/*.jsx bin/*
```

Its picking up all js and jsx files in subfolders and evey file in bin (like `blah.anything`)

**Comment by Flet** [comment]
Oh, maybe I'm misunderstanding this... You're trying to achieve this programmatically?

**Comment by joshuajabbour** [comment]
So the problem is that bash is expanding those stars _before_ they ever get to standard/deglob/glob. If you log out the `argv._`, you already have the expanded file list. So these heavily depend on your user settings (I have bash setup with globstar, so I get what you do, but other teams members don't). 

That's what I meant by maybe this being a glob module issue, but I can't find a way to pass `**/*.js **/*.jsx bin/*` to this module so that bash ignores it and glob does the expansion...

**Comment by feross** [comment]
@joshuajabbour 

Try this:

```bash
standard "**/*.js" "**/*.jsx" "bin/*"
```

The quotes prevent your shell from trying to interpret the stars.

**Comment by joshuajabbour** [comment]
Ah yes, that does it. I was trying `standard "**/*.js */*.jsx bin/*"`, which was failing because it wasn't an array of paths. Doh! Thanks

**Comment by feross** [comment]
@joshuajabbour Cheers@!
